### ISSUE TITLE
IllegalArgumentException when using Embrace.crash

### ISSUE THREAD

**Issue by ngsanti** [yongjhih/flutter_embrace#3]
flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.6-pre.32, on Linux, locale en_PH.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

• No issues found!
```

stack trace:
```
E/MethodChannel#flutter_embrace(19544): Failed to handle method call
E/MethodChannel#flutter_embrace(19544): java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.StackTraceElement;@da0a5d1
E/MethodChannel#flutter_embrace(19544): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#flutter_embrace(19544): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#flutter_embrace(19544): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
E/MethodChannel#flutter_embrace(19544): 	at io.embrace.android.embracesdk.FlutterEmbracePluginKt.errors(FlutterEmbracePlugin.kt:255)
E/MethodChannel#flutter_embrace(19544): 	at io.embrace.android.embracesdk.FlutterEmbracePluginKt.error(FlutterEmbracePlugin.kt:256)
E/MethodChannel#flutter_embrace(19544): 	at io.embrace.android.embracesdk.FlutterEmbracePluginKt.complete(FlutterEmbracePlugin.kt:305)
E/MethodChannel#flutter_embrace(19544): 	at io.embrace.android.embracesdk.FlutterEmbracePlugin.onMethodCall(FlutterEmbracePlugin.kt:208)
E/MethodChannel#flutter_embrace(19544): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter_embrace(19544): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter_embrace(19544): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter_embrace(19544): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_embrace(19544): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_embrace(19544): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter_embrace(19544): 	at android.app.ActivityThread.main(ActivityThread.java:6806)
E/MethodChannel#flutter_embrace(19544): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_embrace(19544): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter_embrace(19544): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (19544): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unsupported value: [Ljava.lang.StackTraceElement;@da0a5d1, null)
E/flutter (19544): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (19544): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (19544): <asynchronous suspension>
E/flutter (19544): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (19544): #3      main.<anonymous closure> (package:kalibrr_flutter/main.dart:30:21)
E/flutter (19544): #4      _rootRunBinary (dart:async/zone.dart:1150:13)
E/flutter (19544): #5      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
E/flutter (19544): #6      runZoned.<anonymous closure> (dart:async/zone.dart:1481:21)
E/flutter (19544): #7      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
E/flutter (19544): #8      Future._propagateToListeners (dart:async/future_impl.dart:598:16)
E/flutter (19544): #9      Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter (19544): #10     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:15)
```

**Comment by yongjhih** [comment]
That's a known issue, `Embrace.crash()` not ready to use for now.
